### ISSUE TITLE
It doesn't work for me 

### ISSUE THREAD

**Issue by ghost** [TrianguloY/webhook-discord#3]
I tried to do this  and everything should be exactly the same but I get this response 

"      Invalid request, for more information go to the <a href="https://github.com/TrianguloY/webhook-discord">GitHub page</a>"

**Comment by TrianguloY** [comment]
I did a few checks and it is working for me.

Is that message displayed when you try to access the url by the browser? note that this page was made to be used by a POST petition, once configured you don't need to access the browser.

In any case, I just updated the page to display a button if a GET request is performed, that will trigger a 'test' message for testing purposes. Hope this helps you, otherwise please try to describe with a bit more details the steps you followed. (this is already deployed on my sample server, if you made your own copy you will need to update it)

**Comment by ghost** [comment]
Thank you now this it works
